// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oiffxwoitkoiefdvvara.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pZmZ4d29pdGtvaWVmZHZ2YXJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MzU1MzEsImV4cCI6MjA1NzIxMTUzMX0.rhSc_3rpv8JNr0bWkpLdqq045KUzIa4GeEAkAQ_K7Qk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);